### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by spiray**
I added the `.eslintrc.js` file. Once this is approved and merged i will start linting all `.js` files. Thanks!

### CODE REVIEW

**Comment by MathuraMG** [comment]
Hey @spiray - not sure if you saw our comments in the previous [PR](https://github.com/processing/p5.accessibility/pull/68), let us know if you would like to reopen that, or go ahead with this!

**Comment by spiray** [comment]
Hi @MathuraMG I did see them. I had a religious holiday so i had take some time off. I will get organized with how i work on this but i think it will be best to move forward with this one. The other changes didn't take much time.

**Comment by MathuraMG** [comment]
@spiray - that sounds good! We will review this then.
Hope you had a good holiday :)

**Comment by MathuraMG** [comment]
@spiray - the eslint file looks to be a good starter file. Can we also add [quotes](https://eslint.org/docs/rules/quotes) for this version? (it helps making the code look clean :))

@lm-n - What do you think?

**Comment by spiray** [comment]
I didn't notice any double quotes so i didn't think it was needed but i can add it in.

**Comment by MathuraMG** [comment]
@spiray - that sounds like a good idea

**Comment by lm-n** [comment]
@spiray I'm closing this so that we can continue on #72

**Pull request closed without merging**
