### PR TITLE
Modes

### PR DESCRIPTION
**Pull request by mithru**
My apologies if lint errors exist. I'll fix them. Before that, I just want to run this by you to check if I'm heading in the proper approach. 

issue being resolved is #43 . This PR is only for ellipseMode. Just want to run this by you before I implement rectMode and colorMode

Also, correct me if I'm wrong, but for the command
`npm run lint `
to run, `lint` should be specified as a script in package.json ,  right? Am I missing something?

### CODE REVIEW

**Comment by spiray** [comment]
@MathuraMG Do you want me to add a lint script? We can eventually include it in the CI. It would just be `eslint src/`. Or maybe we can combine the lint and build into one script...?

**Comment by MathuraMG** [comment]
@mithru - the code looks good.  The one thing I am concerned about is that it looks like it will now read - *red ellipse center* instead of *red ellipse*. 
I feel like that would be confusing. It makes sense to mention it when it is NOT at the center. What do you think ? @lm-n 

@spiray - I like the idea of combining the lint and the build. That way, we will be forced to lint it when we build.

**Comment by MathuraMG** [comment]
@mithru  - Just wanted to follow up on this PR

**Comment by lm-n** [comment]
@MathuraMG @mithru totally agree with Mathura on this I think it should read "red ellipse". I wonder if we should only consider ellipse mode in the way we parse through the values in order to create the text but keep the text itself the same without mentioning the mode.

**Comment by mithru** [comment]
oops sorry. was at makerfaire prepping for another project. I think I missed the "red ellipse center" part. I originally added that to help me debug while I was adding it. Will edit it

**Comment by mithru** [comment]
removed it for now. This PR basically doesn't change the way it's displayed, but takes into account the mode of ellipse when calculating area - previously, using a different mode would break how we calculate area (#43 ).

**Comment by MathuraMG** [comment]
@mithru  - looks good :) !

**Comment by lm-n** [comment]
@mithru just an FYI there are errors that the linting shows that we should resolve and have nothing to do with this PR

**Comment by mithru** [comment]
Too many merge conflicts. I'm closing this. check #98 please? That's the same code with no lint errors.

**Pull request closed without merging**
